const router = require("express").Router();
const user = require("./users");
const slider = require("./slider");
const faq = require("./faq");
const about = require("./about");
const aboutBanner = require("./aboutBanner");
const aboutARCF = require("./aboutARCF");
const chairman = require("./chairman");
const currentChairman = require("./currentChairman");
const viceChairman = require("./viceChairman");
const assistantViceChairman = require("./assistantViceChairman");
const director = require("./director");
const management = require("./management");
const volunteer = require("./volunteer");
const projects = require("./projects");
const projectBanner = require("./projectBanner");
const projectDetails = require("./projectDetails");

const newsBanner = require("./newsBanner");
const newsDetails = require("./newsDetails");
const news = require("./news");
const contactSlider = require("./contactSlider");
const newsCategoryDescription = require("./newsCategoryDescription");
const events = require("./events");
const eventsBanner = require("./eventsBanner");
const eventsDetails = require("./eventsDetails");
const eventsCategoryDescription = require("./eventsCategoryDescription");

// const health = require("./health");
const healthBanner = require("./healthBanner");
// const healthDetails = require("./healthDetails");
// const healthCategoryDetails = require("./healthCategoryDetails");
const projectSubCategory = require("./projectSubCategory");

const projectSubCategoryDetails = require("./projectSubCategoryDetails");
const projectSubCategoryHeader = require("./projectSubCategoryHeader");
const projectSubCategoryDetailsHeader = require("./projectSubCategoryDetailsHeader");
const ProjectSubCategoryDescription = require("./projectSubCategoryDescription");
const contact = require("./contact");
const galleryCategoryDescription = require("./galleryCategoryDescription");
const imageGallery = require("./imageGallery");
const videoGallery = require("./videoGallery");
const donationCategoryDescription = require("./donationCategoryDescription");
const donation = require("./donation");

router.use("/user", user);
router.use("/slider", slider);
router.use("/faq", faq);
router.use("/about", about);
router.use("/banner", aboutBanner);
router.use("/aboutARCF", aboutARCF);
router.use("/chairman", chairman);
router.use("/currentChairman", currentChairman);
router.use("/viceChairman", viceChairman);
router.use("/assistantViceChairman", assistantViceChairman);
router.use("/director", director);
router.use("/management", management);
router.use("/volunteer", volunteer);
router.use("/projectBanner", projectBanner);
router.use("/projectDetails", projectDetails);
router.use("/newsBanner", newsBanner);
router.use("/newsDetails", newsDetails);
router.use("/news", news);
router.use("/newsCategoryDescription", newsCategoryDescription);
router.use("/events", events);
router.use("/eventsDetails", eventsDetails);
router.use("/eventsBanner", eventsBanner);
router.use("/eventsCategoryDescription", eventsCategoryDescription);

// router.use("/health", health);
router.use("/healthBanner", healthBanner);
router.use("/contact", contact);
router.use("/contactSlider", contactSlider);
// router.use("/healthDetails", healthDetails);
// router.use("/healthCategoryDetails", healthCategoryDetails);
router.use("/projects", projects);
router.use("/projectSubCategory", projectSubCategory);
router.use("/projectSubCategoryDetails", projectSubCategoryDetails);
router.use("/projectSubCategoryHeader", projectSubCategoryHeader);
router.use("/projectSubCategoryDetailsHeader", projectSubCategoryDetailsHeader);
router.use("/projectSubCategoryDescription", ProjectSubCategoryDescription);
router.use("/galleryCategoryDescription", galleryCategoryDescription);
router.use("/imageGallery", imageGallery);
router.use("/videoGallery", videoGallery);
router.use("/donationCategoryDescription", donationCategoryDescription);
router.use("/donation", donation);

module.exports = router;
